/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth.register'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthConfirmEmailRouteImport } from './routes/_auth.confirm-email'
import { Route as AppReunioesRouteImport } from './routes/_app.reunioes'
import { Route as AppReservasRouteImport } from './routes/_app.reservas'
import { Route as AppInicioRouteImport } from './routes/_app.inicio'
import { Route as AppFinanceiroRouteImport } from './routes/_app.financeiro'
import { Route as AppDocumentosRouteImport } from './routes/_app.documentos'
import { Route as AppCorrespondenciasRouteImport } from './routes/_app.correspondencias'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppAvisosRouteImport } from './routes/_app.avisos'
import { Route as AppAdministradoraRouteImport } from './routes/_app.administradora'
import { Route as AppAcessosRouteImport } from './routes/_app.acessos'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const AppReunioesRoute = AppReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AppRoute,
} as any)
const AppReservasRoute = AppReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AppRoute,
} as any)
const AppInicioRoute = AppInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppCorrespondenciasRoute = AppCorrespondenciasRouteImport.update({
  id: '/correspondencias',
  path: '/correspondencias',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministradoraRoute = AppAdministradoraRouteImport.update({
  id: '/administradora',
  path: '/administradora',
  getParentRoute: () => AppRoute,
} as any)
const AppAcessosRoute = AppAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AppAcessosRoute
  '/administradora': typeof AppAdministradoraRoute
  '/avisos': typeof AppAvisosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/correspondencias': typeof AppCorrespondenciasRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/inicio': typeof AppInicioRoute
  '/reservas': typeof AppReservasRoute
  '/reunioes': typeof AppReunioesRoute
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AppAcessosRoute
  '/administradora': typeof AppAdministradoraRoute
  '/avisos': typeof AppAvisosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/correspondencias': typeof AppCorrespondenciasRoute
  '/documentos': typeof AppDocumentosRoute
  '/financeiro': typeof AppFinanceiroRoute
  '/inicio': typeof AppInicioRoute
  '/reservas': typeof AppReservasRoute
  '/reunioes': typeof AppReunioesRoute
  '/confirm-email': typeof AuthConfirmEmailRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/acessos': typeof AppAcessosRoute
  '/_app/administradora': typeof AppAdministradoraRoute
  '/_app/avisos': typeof AppAvisosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/correspondencias': typeof AppCorrespondenciasRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/financeiro': typeof AppFinanceiroRoute
  '/_app/inicio': typeof AppInicioRoute
  '/_app/reservas': typeof AppReservasRoute
  '/_app/reunioes': typeof AppReunioesRoute
  '/_auth/confirm-email': typeof AuthConfirmEmailRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/administradora'
    | '/avisos'
    | '/configuracoes'
    | '/correspondencias'
    | '/documentos'
    | '/financeiro'
    | '/inicio'
    | '/reservas'
    | '/reunioes'
    | '/confirm-email'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/administradora'
    | '/avisos'
    | '/configuracoes'
    | '/correspondencias'
    | '/documentos'
    | '/financeiro'
    | '/inicio'
    | '/reservas'
    | '/reunioes'
    | '/confirm-email'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/acessos'
    | '/_app/administradora'
    | '/_app/avisos'
    | '/_app/configuracoes'
    | '/_app/correspondencias'
    | '/_app/documentos'
    | '/_app/financeiro'
    | '/_app/inicio'
    | '/_app/reservas'
    | '/_app/reunioes'
    | '/_auth/confirm-email'
    | '/_auth/login'
    | '/_auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/confirm-email': {
      id: '/_auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/reunioes': {
      id: '/_app/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AppReunioesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reservas': {
      id: '/_app/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AppReservasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inicio': {
      id: '/_app/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AppInicioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/financeiro': {
      id: '/_app/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/correspondencias': {
      id: '/_app/correspondencias'
      path: '/correspondencias'
      fullPath: '/correspondencias'
      preLoaderRoute: typeof AppCorrespondenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/avisos': {
      id: '/_app/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/administradora': {
      id: '/_app/administradora'
      path: '/administradora'
      fullPath: '/administradora'
      preLoaderRoute: typeof AppAdministradoraRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acessos': {
      id: '/_app/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AppAcessosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcessosRoute: typeof AppAcessosRoute
  AppAdministradoraRoute: typeof AppAdministradoraRoute
  AppAvisosRoute: typeof AppAvisosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCorrespondenciasRoute: typeof AppCorrespondenciasRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppInicioRoute: typeof AppInicioRoute
  AppReservasRoute: typeof AppReservasRoute
  AppReunioesRoute: typeof AppReunioesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcessosRoute: AppAcessosRoute,
  AppAdministradoraRoute: AppAdministradoraRoute,
  AppAvisosRoute: AppAvisosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCorrespondenciasRoute: AppCorrespondenciasRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppInicioRoute: AppInicioRoute,
  AppReservasRoute: AppReservasRoute,
  AppReunioesRoute: AppReunioesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
